### ISSUE TITLE
setCacheMLSResults || setNumberOfThreads

### ISSUE THREAD

**Issue by alitokur** [danielTobon43/upsamplingCloudPCL#1]
hi sir, when I try to build with pcl 1.8.1 I get the following errors

```
error: ‘class pcl::MovingLeastSquares<pcl::PointXYZRGB, pcl::PointXYZRGB>’ has no member named ‘setCacheMLSResults’; did you mean ‘MLSResult’?
     mls.setCacheMLSResults(true);//Set whether the mls results should be stored for each point in the input cloud.

error: ‘class pcl::MovingLeastSquares<pcl::PointXYZRGB, pcl::PointXYZRGB>’ has no member named ‘setNumberOfThreads’
     mls.setNumberOfThreads(num_threats);
```

do you have any idea?

**Comment by alitokur** [comment]
hi sir, when I try to build with pcl 1.8.1 I get the following errors

```
error: ‘class pcl::MovingLeastSquares<pcl::PointXYZRGB, pcl::PointXYZRGB>’ has no member named ‘setCacheMLSResults’; did you mean ‘MLSResult’?
     mls.setCacheMLSResults(true);//Set whether the mls results should be stored for each point in the input cloud.

error: ‘class pcl::MovingLeastSquares<pcl::PointXYZRGB, pcl::PointXYZRGB>’ has no member named ‘setNumberOfThreads’
     mls.setNumberOfThreads(num_threats);
```


do you have any idea?

**Comment by ghost** [comment]
Hi @alitokur , I guess the error is related to the PCL version you have. Because this project was tested on PCL 1.9.1

**Comment by ghost** [comment]
> hi sir, when I try to build with pcl 1.8.1 I get the following errors
> 
> ```
> error: ‘class pcl::MovingLeastSquares<pcl::PointXYZRGB, pcl::PointXYZRGB>’ has no member named ‘setCacheMLSResults’; did you mean ‘MLSResult’?
>      mls.setCacheMLSResults(true);//Set whether the mls results should be stored for each point in the input cloud.
> 
> error: ‘class pcl::MovingLeastSquares<pcl::PointXYZRGB, pcl::PointXYZRGB>’ has no member named ‘setNumberOfThreads’
>      mls.setNumberOfThreads(num_threats);
> ```
> 
> do you have any idea?

Hi @alitokur, after reading pcl documentation. It seems the problem is with the way that you are compiling the program. Are you using CMake for this?

**Comment by alitokur** [comment]
@danielTobon43 hola, yep i use cmake (actually i don't know any way to use PCL without cmake). I'll upgrade it.

**Comment by ghost** [comment]
Hi @alitokur. I have tried this program with PCL 1.8.1 and is working. What I understand, the issue is related to the import of the PCL library into the main program. So, could be something in the CMakeLists.txt.

**Comment by alitokur** [comment]
I just use "find package" instead of the setting PCL path. it's kinda something:


```

cmake_minimum_required(VERSION 3.5.1 FATAL_ERROR)

# set project name
project(upsampling_cloud VERSION 1.0.0 LANGUAGES CXX)

# set build type = Release mode
set(CMAKE_BUILD_TYPE Release)

find_package(PCL REQUIRED)
include_directories(
  ${PCL_INCLUDE_DIRS}
)

include(CheckFunctionExists)
add_definitions(${PCL_DEFINITIONS})
link_directories(
                 ${PCL_LIBRARY_DIRS}                
)


set(MAIN_SOURCE "main.cpp")
add_executable(${PROJECT_NAME}                
               ${MAIN_SOURCE}
)
               

target_link_libraries(${PROJECT_NAME}                      
                      ${PCL_LIBRARIES}

                      )
```

**Comment by ghost** [comment]
Hi @alitokur, could you tell me how did you compile PCL?
are you using linux or windows?, did you set your PCL build directory in the` CMakeLists.txt`? 

the "`PATHS`" argument in find_package is because I don't have PCL installed on my laptop (just compiled) and because of that, I need to set the path to the BUILD directory, but if you have installed PCL on your laptop you don't need the `PATHS` argument, just the version, e.g

`find_package(PCL 1.8 REQUIRED)`
